### ISSUE TITLE
<legacy> Previous platformUrl lingers around.

### ISSUE THREAD

**Issue by cpoppema** [vialer/vialer-js#126]
**Describe the bug**
Cannot succesfully login after changing platformUrl.

**To Reproduce**
1. Go to options
2. Change the platformUrl
3. Login with a user on that new platform
4. See error in the background page:
```
POST https://partner.voipgrid.nl/api/permission/apitoken/ 400 (Bad Request) ... webext_bg.js:1
```

The url that is in the error is the _previous_ platformUrl.

**Expected behavior**
It works after restarting the browser, this should not be a necessary step.

**Environment (please complete the following information):**
v2.2.1

**Comment by jvanveen** [comment]
Legacy (wont fix)

**Comment by ghost** [comment]
Moved this to JIRA https://voipgrid.atlassian.net/browse/VIALJS-103. Tickets here are only concerning the opensource build.
