### ISSUE TITLE
Overlapping text in options popup

### ISSUE THREAD

**Issue by cpoppema** [vialer/vialer-js#127]
**Describe the bug**
Overlapping text in options popup

**To Reproduce**
1. Go to options
2. Change platformUrl
4. See screenshot

**Expected behavior**
A readable warning text.

**Screenshots**
![2018-06-13-1528882980_screenshot](https://user-images.githubusercontent.com/1432901/41343512-21a99fba-6eff-11e8-88bf-99cb22573352.png)

**Environment (please complete the following information):**
v2.2.1

**Comment by ghost** [comment]
Legacy (wont fix)
