### ISSUE TITLE
Queue information is not refreshed until a queue is selected

### ISSUE THREAD

**Issue by cpoppema** [vialer/vialer-js#128]
**Describe the bug**
If you open the plugin popup it doesn't refresh the queue information (numbers in front of the queues) without selecting a queue first.

**To Reproduce**
1. Open /client/\<id\>/queue/ as the background page.
1. Open the plugin popup.
2. Setup a call to end up in a queue.
3. Wait.
4. See the numbers for the queue in the background page increase.
5. The popup never refreshes.
6. Select a queue.
7. Wait.
8. The popup refreshes!

**Expected behavior**
Selecting a queue should not be necessary to poll for queue updates.

**Environment (please complete the following information):**
v2.2.1

**Additional context**
v1.x used to:
- not poll at all if the popup is closed
- poll every 20 seconds if the popup is closed and a queue is selected (to update the plugin's icon)
- poll every 5 seconds if the popup is open

You can see the (lack of) api calls to /api/queuecallgroup/ in the background page.

**Comment by ghost** [comment]
Legacy (wont fix)
