### ISSUE TITLE
How to get user credentials to use the extension ?

### ISSUE THREAD

**Issue by sincerekamal** [vialer/vialer-js#172]
**Describe the bug**
How to get user credentials to use the extension ?

**To Reproduce**
1. Clone the repo
2. Build and install as given
3. On clicking Browser icon, it shows login form, but where to register ?

**Comment by ghost** [comment]
Hi!

Good question. The develop branch still has hardcoded dependencies. I'm a couple of days away from merging https://github.com/vialer/vialer-js/tree/feature/restructure-module-loading, which separates all vendor specific logic. So on develop for now you need a VoIPGRID account, but when the work in the other branch is done, you can use the voip user adapter to login to any sip provider that supports sip over websocket & webrtc.

**Comment by ghost** [comment]
The current develop branch has a default build called Bologna, which builds as a generic softphone. There are some references on the documentation site (https://vialer-js.io) on how to setup a sip-over-websocket backend. Otherwise you would need a VoIP provider that supports this functionality.
